### ISSUE TITLE
Wrong mapping

### ISSUE THREAD

**Issue by Pouya-moh** [cogimon/rtt-gazebo-robot-sim#13]
I did a test, sending joint angels to "LElbj" but instead shoulder joint moved. Printing mapping, shows that "LElbj" is mapped to index=0. FYI, these are the rest:

```
LElbj           0
LForearmPlate   1
LShLat          2
LShSag          3
LShYaw          4
LWrj1           5
LWrj2           6

```

**Comment by EnricoMingo** [comment]
Did u pull?
Il 13/giu/2016 23:21, "Pouya" <notifications@github.com> ha scritto:

**Comment by EnricoMingo** [comment]
Solved
